DATASETS:
  LABELED_TRAIN: ("voc_2007_trainval",)
  UNLABELED_TRAIN: ("voc_2012_trainval",)
  TEST: ("voc_2007_test",)
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 600
SOLVER:
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16